[project]
name = "combine-movie"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "isort>=6.0.1",
    "numpy==2.2.2",
    "opencv-python==4.11.0.86",
    "ruff>=0.12.2",
    "tqdm==4.66.2",
]
